name: owasp_zap
on:
  workflow_dispatch:
  workflow_call:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: ./mvnw clean install

      - name: Build Docker Image
        run: docker build -t my-app:${{ github.sha }} .

      - name: Use Docker to start the application locally
        run: docker run -it -p 127.0.0.1:8080:8080 -p 127.0.0.1:9090:9090 my-app:${{ github.sha }}
        
      - name: Change wait-for-it permissions
        run: chmod +x wait-for-it.sh
        
      - name: Wait for the application
        run: ./wait-for-it.sh localhost:8080
        
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.11.0
        with:
          target: "http://host.docker.internal:8080"
          artifact_name: "zap_results"
          
      - name: Upload result to GitHub Code Scanning
        uses: actions/upload-artifact@v3
        with:
          name: zap_results
          path: report_html.html
